name: Generate remaining diffs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-diffs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run generate-all-missing-diffs script
        run: bun generate-all-missing-diffs
        timeout-minutes: 300
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Generate new diffs
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: new-diffs
          delete-branch: true
          title: "Generate new diffs"
